### PR TITLE
MAINT: update meta standards

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

With the merge of pysat/pysat#634, the metadata labels 'plot', 'axis', and 'scale' are no longer supported.  This removes those here.

# Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Pytest with appropriate pysat branch (develop-3)

## Test Configuration
* Operating system: Mac 10.15.7
* Version number: Python 3.8.2

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release

### CODE REVIEW

**Review by aburrell — APPROVED** [review]
Looks good!  Wasn't sure if you'd want to merge into rc or develop, but either way is fine from my perspective.  RC is going to not work in a week or two anyway.

**Comment by aburrell** [comment]
@jklenzing I took this opportunity to future proof this project against the next set of meta changes as well.

**Comment by jklenzing** [comment]
Merging into the rc branch makes sense, as it will buy us a little time with a green badge on the front page.  Also, are the badges updated to travis.com there?  If not, I can fix that here too.

**Comment by aburrell** [comment]
Ok @jklenzing this is good to merge!

**Pull request merged**
