### PR TITLE
Dst update

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #56 

Fixed multi-day data loading issue. Also improved efficiency when loading multiple days, plus, I added metadata.

# Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

```
start_date = dt.datetime(2001, 1, 1)
end_date = dt.datetime(2001, 12, 31)
dst = pysat.Instrument('sw', 'dst')
dst.load(date=start_date, end_date=end_date)
dst['dst'].plot(title=dst.meta['dst', dst.meta.labels.name], 
                ylabel=dst.meta['dst', dst.meta.labels.units])
```

image

## Test Configuration
* Operating system: Mac OS 10.15.4
* Version number: Python 3.8.3

# Checklist:

- [ ] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release

### CODE REVIEW

**Comment by aburrell** [comment]
I made some changes to partially address #59

**Review by aburrell — COMMENTED** [review]
I just made changes instead of requesting them.  Tell me what you think @rstoneback

**Comment by rstoneback** [comment]
> I just made changes instead of requesting them. Tell me what you think @rstoneback

Fair enough. Good catch on the missing return. Adding a 'noaa' tag certainly makes it easy to extend to other data sources in the future. My only hesitation is it makes instantiating slightly harder but it does also make code written today more robust against future changes. Works for me.

**Comment by rstoneback** [comment]
I have a draft pull over at pysatTutorials. My initial thinking was it could be good to have demos of the various pysatSpaceWeather instruments over there. Here is a simple example for Dst,
https://github.com/pysat/pysatTutorials/pull/4

Then I wondered how many we want to maintain, plus what is the balance against examples in the documentation. Topics for a telecom perhaps and outside this pull. Still, leaving this note here given the specific connection to dst. It is the reason I found the bug.

**Review by jklenzing — APPROVED** [review]
Looks good to me.

**Pull request merged**
